name: Build and Release
on:
  push:
    tags:
      - 'v*' # This triggers the build whenever you push a tag like v1.0.0
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI

jobs:
  release:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install

      - name: Download Binaries
        run: |
          # Create folders
          mkdir -p binaries/x64 binaries/arm64
          
          # Download Intel (x64) binaries
          curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b6.1.1/darwin-x64 -o binaries/x64/ffmpeg
          curl -L https://github.com/eugeneware/ffprobe-static/releases/download/b6.1.1/darwin-x64 -o binaries/x64/ffprobe
          
          # Download Apple Silicon (arm64) binaries
          curl -L https://github.com/eugeneware/ffmpeg-static/releases/download/b6.1.1/darwin-arm64 -o binaries/arm64/ffmpeg
          curl -L https://github.com/eugeneware/ffprobe-static/releases/download/b6.1.1/darwin-arm64 -o binaries/arm64/ffprobe
          
          # Make them executable
          chmod +x binaries/x64/ffmpeg binaries/x64/ffprobe binaries/arm64/ffmpeg binaries/arm64/ffprobe

      - name: Build and Sign (MAS)
        run: npm run dist:mas
        env:
          ELECTRON_BUILDER_ALLOW_EMPTY_ARCHIVE: true
          APPLE_TEAM_ID: K86UCD782J
          USE_HARD_LINKS: false
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_INSTALLER_LINK: ${{ secrets.CSC_INSTALLER_LINK }}
          CSC_INSTALLER_KEY_PASSWORD: ${{ secrets.CSC_INSTALLER_KEY_PASSWORD }}
          PROVISIONING_PROFILE: ${{ secrets.PROVISION_PROFILE_BASE64 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Track-Trimmer-Pro-Package
          path: dist/**/*.pkg
          if-no-files-found: error
